// Server entry point
process.on('uncaughtException', (err) => {
  console.error('UNCAUGHT EXCEPTION! 💥', err);
  if (process.env.NODE_ENV === 'production') process.exit(1);
});

process.on('unhandledRejection', (err: any) => {
  console.error('UNHANDLED REJECTION! 💥', err);
  if (process.env.NODE_ENV === 'production') process.exit(1);
});

import express from "express";
import dns from "dns";
import path from "path";
import cors from "cors";
import dotenv from "dotenv";
import { createServer as createViteServer } from "vite";
import admin from "firebase-admin";

// FORCE IPv4 globally for the process to avoid ENETUNREACH on IPv6
if (dns && (dns as any).setDefaultResultOrder) {
  (dns as any).setDefaultResultOrder('ipv4first');
}

// Modular Imports
import * as DB from "./server/db";
import { initSDKs } from "./server/init";
import { setupRoutes } from "./server/routes";
import { setupGeminiRoute } from "./server/gemini";
import { setupVamshavaliRoutes } from "./server/vamshavali-api";
import { setupAuthRoutes } from "./server/auth-api";
import { setupNewsRoutes } from "./server/news-api";
import { setupAIRouter } from "./server/ai-router";
import { setupNumerologyRoutes } from "./server/numerology-api";
import { setupAdminRoutes } from "./server/admin-api";
import { lineageRouter } from "./server/lineage-endpoints";
import { setupSSR } from "./server/ssr";
import { handleTelegramWebhook } from "./server/telegram-bot";
import { autoGenerateDailyNews, generateDailySanataniFacts } from "./server/background-tasks";
import { getCurrentNewsDate } from "./server/date-utils";

dotenv.config();

const newsLocks = new Map<string, number>();
const lastPhotos = new Map<number, { url: string, timestamp: number }>();
const telegramLinkCache = new Map<number, { profileId: string, timestamp: number }>();

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(cors({ origin: true, credentials: true }));
  app.use(express.json({ limit: '50mb' }));
  app.use(express.urlencoded({ extended: true, limit: '50mb' }));

  // Initialize SDKs
  await initSDKs();
  console.log(`[Server] SDKs initialized. AdminDB: ${!!DB.state.adminDb}, ClientDB: ${!!DB.state.db}, Config: ${!!DB.state.firebaseConfig}`);

  // Telegram Webhook
  app.post("/api/webhooks/telegram", (req, res) => {
    handleTelegramWebhook(req, res, lastPhotos, telegramLinkCache, DB.db, DB.adminDb);
  });

  // Telegram Image Local Proxy to prevent token leakage and allow secure browser rendering
  app.get("/api/telegram-image/*", async (req, res) => {
    try {
      const filePath = req.params[0];
      if (!filePath) {
        return res.status(400).send("File path is required.");
      }

      // Dynamically locate the telegram bot token exactly like we do in the bot code
      const botTokenKey = Object.keys(process.env).find(k => {
        const uk = k.toUpperCase();
        return uk.includes('TELEGRAM') && uk.includes('BOT') && !uk.includes('USER');
      });
      const token = botTokenKey ? process.env[botTokenKey]?.trim() : null;

      if (!token) {
        console.error("[Telegram Image Proxy] Bot token missing from env variables.");
        return res.status(500).send("Telegram bot token not configured.");
      }

      const telegramUrl = `https://api.telegram.org/file/bot${token}/${filePath}`;
      const response = await fetch(telegramUrl);
      
      if (!response.ok) {
        return res.status(response.status).send("Failed to retrieve image from Telegram.");
      }

      const contentType = response.headers.get("content-type") || "image/jpeg";
      res.setHeader("Content-Type", contentType);
      res.setHeader("Cache-Control", "public, max-age=86400"); // cache for 1 day

      const buffer = Buffer.from(await response.arrayBuffer());
      return res.end(buffer);
    } catch (err: any) {
      console.error("[Telegram Image Proxy] Error proxying file:", err);
      return res.status(500).send("Internal server error proxying file.");
    }
  });

  // Setup Routes
  setupRoutes(app, DB.db, DB.adminDb, DB.firebaseConfig, newsLocks);
  setupGeminiRoute(app);
  setupAuthRoutes(app, DB.db, DB.adminDb, admin);
  setupVamshavaliRoutes(app, DB.db, DB.adminDb, admin);
  app.use("/api", lineageRouter);
  setupNewsRoutes(app, DB.db, DB.adminDb, newsLocks, getCurrentNewsDate);
  setupAIRouter(app, DB.db, DB.adminDb, admin);
  setupNumerologyRoutes(app);
  setupAdminRoutes(app, newsLocks);

  let vite: any;
  if (process.env.NODE_ENV !== "production") {
    vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "custom",
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static("dist", { index: false }));
  }

  // SSR handles all other routes
  setupSSR(app, vite);

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`[Server] Running on port ${PORT} in ${process.env.NODE_ENV || 'development'} mode`);
    // Run background tasks with a delay
    setTimeout(() => {
      autoGenerateDailyNews().catch(console.error);
      generateDailySanataniFacts().catch(console.error);
    }, 10000);

    // Backup scheduler: check and auto generate once every 3 hours
    setInterval(() => {
      autoGenerateDailyNews().catch(console.error);
    }, 3 * 60 * 60 * 1000);
  });
}

startServer().catch(err => {
  console.error("FATAL ERROR DURING STARTUP! 💥", err);
  process.exit(1);
});
