// Server entry point
process.on('uncaughtException', (err) => {
  console.error('UNCAUGHT EXCEPTION! 💥', err);
  if (process.env.NODE_ENV === 'production') process.exit(1);
});

process.on('unhandledRejection', (err: any) => {
  console.error('UNHANDLED REJECTION! 💥', err);
  if (process.env.NODE_ENV === 'production') process.exit(1);
});

import express from "express";
import dns from "dns";
import path from "path";
import cors from "cors";
import dotenv from "dotenv";
import { createServer as createViteServer } from "vite";
import admin from "firebase-admin";

// FORCE IPv4 globally for the process to avoid ENETUNREACH on IPv6
if (dns && (dns as any).setDefaultResultOrder) {
  (dns as any).setDefaultResultOrder('ipv4first');
}

// Modular Imports
import { db, adminDb, firebaseConfig } from "./server/db";
import { initSDKs } from "./server/init";
import { setupRoutes } from "./server/routes";
import { setupGeminiRoute } from "./server/gemini";
import { setupVamshavaliRoutes } from "./server/vamshavali-api";
import { setupAuthRoutes } from "./server/auth-api";
import { setupNewsRoutes } from "./server/news-api";
import { setupAIRouter } from "./server/ai-router";
import { setupNumerologyRoutes } from "./server/numerology-api";
import { setupAdminRoutes } from "./server/admin-api";
import { setupSSR } from "./server/ssr";
import { handleTelegramWebhook } from "./server/telegram-bot";
import { autoGenerateDailyNews, generateDailySanataniFacts } from "./server/background-tasks";
import { getCurrentNewsDate } from "./server/date-utils";

dotenv.config();

const newsLocks = new Map<string, number>();
const lastPhotos = new Map<number, { url: string, timestamp: number }>();
const telegramLinkCache = new Map<number, { profileId: string, timestamp: number }>();

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(cors({ origin: true, credentials: true }));
  app.use(express.json({ limit: '50mb' }));
  app.use(express.urlencoded({ extended: true, limit: '50mb' }));

  // Initialize SDKs
  await initSDKs();

  // Telegram Webhook
  app.post("/api/webhooks/telegram", (req, res) => {
    handleTelegramWebhook(req, res, lastPhotos, telegramLinkCache, db, adminDb);
  });

  // Setup Routes
  setupRoutes(app, db, adminDb, firebaseConfig, newsLocks);
  setupGeminiRoute(app);
  setupAuthRoutes(app, db, adminDb, admin);
  setupVamshavaliRoutes(app, db, adminDb, admin);
  setupNewsRoutes(app, db, adminDb, newsLocks, getCurrentNewsDate);
  setupAIRouter(app, db, adminDb, admin);
  setupNumerologyRoutes(app);
  setupAdminRoutes(app, newsLocks);

  let vite: any;
  if (process.env.NODE_ENV !== "production") {
    vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "custom",
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static("dist", { index: false }));
  }

  // SSR handles all other routes
  setupSSR(app, vite);

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`[Server] Running on port ${PORT} in ${process.env.NODE_ENV || 'development'} mode`);
    // Run background tasks with a delay
    setTimeout(() => {
      autoGenerateDailyNews().catch(console.error);
      generateDailySanataniFacts().catch(console.error);
    }, 10000);
  });
}

startServer().catch(err => {
  console.error("FATAL ERROR DURING STARTUP! 💥", err);
  process.exit(1);
});
