import { collection, query, where, limit, getDocs, setDoc, doc, serverTimestamp, writeBatch } from "firebase/firestore";
import admin from "firebase-admin";
import { db, adminDb, firebaseConfig } from "./db";
import { FIRESTORE_SERVER_KEY } from "./constants";
import { getGeminiApiKey, callGeminiWithRetry } from "./gemini";
import { parseGeminiJson, slugify } from "./utils";
import { getCurrentFactDate, getCurrentNewsDate } from "./date-utils";

export async function cleanupOldNews() {
  try {
    const fifteenDaysAgo = new Date();
    fifteenDaysAgo.setDate(fifteenDaysAgo.getDate() - 15);
    const dateStr = fifteenDaysAgo.toISOString().split('T')[0];

    if (adminDb) {
      const oldNews = await adminDb.collection("news").where("date", "<", dateStr).get();
      if (!oldNews.empty) {
        const batch = adminDb.batch();
        oldNews.docs.forEach((doc: any) => batch.delete(doc.ref));
        await batch.commit();
      }
    }
  } catch (error) {
    console.error("[Cleanup] Error:", error);
  }
}

export async function generateDailySanataniFacts() {
  try {
    const today = getCurrentFactDate();
    const apiKey = await getGeminiApiKey(firebaseConfig);
    if (!apiKey) return;
    
    let alreadyExists = false;
    if (adminDb) {
      const existing = await adminDb.collection("fact_checks").where("date", "==", today).limit(1).get();
      alreadyExists = !existing.empty;
    }
    
    if (alreadyExists) return;

    const prompt = `Act as the Sanatani Truth Bot, an AI guardian of Sanatana Dharma. Find 5 current rumors myths about Sanatana Dharma. Perform rigorous fact-check. Respond in JSON array format.`;

    const response = await callGeminiWithRetry(apiKey, {
      model: "gemini-3.1-flash-lite",
      contents: prompt,
      config: { responseMimeType: "application/json" }
    });

    const facts = parseGeminiJson(response.text || '[]');
    
    if (adminDb) {
      const batch = adminDb.batch();
      facts.forEach((fact: any) => {
        const id = slugify(fact.claim).substring(0, 50) + '-' + Math.random().toString(36).substring(2, 7);
        const docRef = adminDb.collection("fact_checks").doc(id);
        batch.set(docRef, { ...fact, date: today, serverKey: FIRESTORE_SERVER_KEY, createdAt: admin.firestore.FieldValue.serverTimestamp() });
      });
      await batch.commit();
      console.log(`[SanataniFacts] Generated ${facts.length} facts for ${today}`);
    }
  } catch (error: any) {
    console.error("[SanataniFacts] Generation Error:", error);
  }
}

export async function autoGenerateDailyNews() {
  try {
    const date = getCurrentNewsDate();
    const apiKey = await getGeminiApiKey(firebaseConfig);
    if (!apiKey) return;

    for (const lang of ['bn', 'en']) {
      const docId = `${date}-${lang}`;
      let exists = false;
      if (adminDb) {
        const snap = await adminDb.collection("news").doc(docId).get();
        exists = snap.exists;
      }
      if (exists) continue;

      const prompt = `Find latest news for ${date} in ${lang}. Respond in JSON format.`;
      const response = await callGeminiWithRetry(apiKey, { 
        model: "gemini-3.1-flash-lite",
        contents: prompt,
        config: { responseMimeType: "application/json" }
      });

      const newsData = parseGeminiJson(response.text || '{}');
      if (adminDb) {
        await adminDb.collection("news").doc(docId).set({ ...newsData, date, updatedAt: new Date().toISOString(), serverKey: FIRESTORE_SERVER_KEY });
        console.log(`[DailyNews] Auto-generated news for ${docId}`);
      }
    }
  } catch (error: any) {
    console.error("[DailyNews] Auto-generation Error:", error);
  }
}
